language: java
jdk:
  - openjdk8
script:
  - mvn test -B
  - mvn clean package jetty:run &
  # sleep to wait for jetty service to be ready
  - sleep 30
  - bash .scripts/buildDB.sh
  - bash .scripts/curl.sh
