language: java
jdk:
  - openjdk8
services:
  - docker
addons:
  apt:
    packages:
      - expect
install:
  - echo "Skip installation"
script:
  - docker-compose build
  - docker-compose up -d
  - ./start_server_background.sh
  - echo "=== Running functional test ==="
  - docker-compose exec identity-functest mvn clean
  - docker-compose exec identity-functest mvn test -Dcucumber.options="--tags @registerTest"
  - docker-compose exec identity-functest mvn test -Dcucumber.options="--tags @loginTest,@updateTest"
